site_name: Mi Notas de Estudio
site_description: Un sitio para organizar mis notas de estudio.

theme:
  name: material
  language: es
  features:
    - content.math
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo oscuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Inicio: index.md
  - Multimedia: multimedia/index.md
  - Fundamentos de Estadística:
      - Introducción: estadistica/index.md
      - Estadística y Probabilidad: estadistica/fundamentos-estadistica-probabilidad.md
      - Estadística Multivariada: estadistica/estadistica-multivariada-y-probabilidad.md
      - Técnicas de Conteo: estadistica/tecnicas-de-conteo-y-probabilidad.md
      - Practica de Probabilidad: estadistica/probabilidad-condicional-y-practica.md
      - Probabilidad Condicional Independiencia y Teorema de Bayes: estadistica/probabilidad-condicional-bayes-variables-aleatorias.md
      - Variables Aleatorias Discretas y Distribuciones de Probabilidad: estadistica/variables-aleatorias-discretas.md
      - Ejercicios de Repaso: estadistica/ejercicios-distribucion-binomial-y-esperanza.md
  - Estadística Aplicada:
      - Temas: estadistica-aplicada/index.md
      - Principales Distribuciones Continuas: estadistica-aplicada/distribuciones-continuas.md
      - Métodos de Muestreo Probabilístico: estadistica-aplicada/introduccion-muestreo.md
      - Distribuciones Muestrales: estadistica-aplicada/distribuciones-muestrales.md
      - Resumen Teorico: estadistica-aplicada/resumen-teorico-est.md
      - Estimación de Parámetros: estadistica-aplicada/estimacion-parametros.md
      - Prueba de Hipotesis: estadistica-aplicada/prueba-hipotesis.md
  - Matematica Financiera:
      - Temas: mate-financiera/index.md
      - Conceptos Basicos: mate-financiera/conceptos-basicos.md
      - Interés Simple: mate-financiera/interes-simple.md
      - Ecuaciones de Valor y Descuento Simple: mate-financiera/ecuaciones-valor-descuento-simple.md
      - Examen 1: mate-financiera/examen-teorico-1.md
      - Interés Compuesto: mate-financiera/interes-compuesto.md
  - Economia:
      - Temas: economia/index.md
      - Los 12 Principios de la Economía: economia/principios.md
      - Resumen Teórico: economia/resumen-teorico.md
      - U2 Calculo de Indicadores Macro PBI: economia/u2-indicadores-macro-pbi.md
  - Derecho Empresarial:
      - Temas: derecho-emp/index.md
      - LGS y Sociedades: derecho-emp/lgs-sociedades.md
      - Reorganizacion y Transformación: derecho-emp/reorganizacion.md
      - Ejemplo PC2: derecho-emp/ejm-exam-pc2.md

#   - Ingles:
#       - Introducción: ingles/index.md
#       - Gramática: ingles/gramatica.md
#       - Vocabulario: ingles/vocabulario.md
#       - Básico 8: ingles/basic08.md
#   - Java:
#       - Introducción: java/index.md
#       - Java SE:
#           - Indice: java/java-se/index.md
#           - Vectores: java/java-se/vectores.md
#           - Matrices: java/java-se/matrices.md
#           - Modelo de Capas: java/java-se/modelo-de-capas.md
#       - POO:
#           - Indice: java/poo/index.md
#           - Clases y Objetos: java/poo/clases-objetos-y-metodos.md
#           - Abstracción, Herencia, Polimorfismo y Encapsulamiento: java/poo/abstraccion-herencia-polimorfismo-encapsulamiento.md
#           - Collections Framework: java/poo/collections.md
#           - Excepciones: java/poo/excepciones.md
#           - Relaciones entre Clases: java/poo/relaciones-entre-clases.md
#           - ORM y JPA (CRUD): java/poo/orm-jpa-crud.md
#           - Hilos (Threads): java/poo/hilos.md
#           - Utils y Generics: java/poo/utils-generics.md


markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:        # ← Activa el resaltado mejorado
      anchor_linenums: true    #   Permite enlazar líneas específicas
      line_spans: __span       #   Necesario para resaltar líneas
      pygments_lang_class: true
  - pymdownx.inlinehilite      # ← Resaltado en código inline `como este`
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html

extra_css:
  # - assets/katex/katex.min.css

extra_javascript:
  - assets/mathjax/mathjax-init.js
  - assets/mathjax/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
  # - assets/katex/katex.min.js
  # - assets/katex/auto-render.min.js
  # - assets/katex/katex-init.js
