site_name: Mi Notas de Estudio
site_description: Un sitio para organizar mis notas de estudio.

theme:
  name: material
  language: es
  features:
    - content.math
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.code.select
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo oscuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Inicio: index.md
  - Fundamentos de Estadística:
      - Introducción: estadistica/index.md
      - Estadística y Probabilidad: estadistica/fundamentos-estadistica-probabilidad.md
      - Estadística Multivariada: estadistica/estadistica-multivariada-y-probabilidad.md
      - Técnicas de Conteo: estadistica/tecnicas-de-conteo-y-probabilidad.md
      - Practica de Probabilidad: estadistica/probabilidad-condicional-y-practica.md
      - Probabilidad Condicional Independiencia y Teorema de Bayes: estadistica/probabilidad-condicional-bayes-variables-aleatorias.md
      - Variables Aleatorias Discretas y Distribuciones de Probabilidad : estadistica/variables-aleatorias-discretas.md
      - Ejercicios de Repaso: estadistica/ejercicios-distribucion-binomial-y-esperanza.md
  - Ingles:
      - Introducción: ingles/index.md
      - Gramática: ingles/gramatica.md
      - Vocabulario: ingles/vocabulario.md
      - Básico 8: ingles/basic08.md
  - Java:
      - Introducción: java/index.md
      - Java SE:
          - Indice: java/java-se/index.md
          - Vectores: java/java-se/vectores.md
          - Matrices: java/java-se/matrices.md
          - Modelo de Capas: java/java-se/modelo-de-capas.md
      - POO:
          - Indice: java/poo/index.md
          - Clases y Objetos: java/poo/clases-objetos-y-metodos.md
          - Abstracción, Herencia, Polimorfismo y Encapsulamiento: java/poo/abstraccion-herencia-polimorfismo-encapsulamiento.md
          - Collections Framework: java/poo/collections.md


markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:        # ← Activa el resaltado mejorado
      anchor_linenums: true    #   Permite enlazar líneas específicas
      line_spans: __span       #   Necesario para resaltar líneas
      pygments_lang_class: true
  - pymdownx.inlinehilite      # ← Resaltado en código inline `como este`

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
