site_name: Mi Notas de Estudio
site_description: Un sitio para organizar mis notas de estudio.

theme:
  name: material
  language: es
  features:
    - content.math
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Modo oscuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Inicio: index.md
  - Fundamentos de Estadística:
      - Introducción: estadistica/index.md
      - Estadística y Probabilidad: estadistica/fundamentos-estadistica-probabilidad.md
      - Estadística Multivariada: estadistica/estadistica-multivariada-y-probabilidad.md
      - Técnicas de Conteo: estadistica/tecnicas-de-conteo-y-probabilidad.md
      - Practica de Probabilidad: estadistica/probabilidad-condicional-y-practica.md
      - Probabilidad Condicional Independiencia y Teorema de Bayes: estadistica/probabilidad-condicional-bayes-variables-aleatorias.md
      - Variables Aleatorias Discretas y Distribuciones de Probabilidad : estadistica/variables-aleatorias-discretas.md
      - Ejercicios de Repaso: estadistica/ejercicios-distribucion-binomial-y-esperanza.md
  - Ingles:
      - Introducción: ingles/index.md
      - Gramática: ingles/gramatica.md
      - Vocabulario: ingles/vocabulario.md
      - Básico 8: ingles/basic08.md
  - POO (Programación Orientada a Objetos):
      - Introducción: poo/index.md
      - Clases y Objetos: poo/clases-objetos-y-metodos.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
